module.exports = {
	CREATE_LIST: 'CREATE_LIST',
	MOVE_MESSAGE: 'MOVE_MESSAGE',
	ARCHIVE_MESSAGE: 'ARCHIVE_MESSAGE',
	DELETE_MESSAGE: 'DELETE_MESSAGE',
	CREATE_MESSAGE: 'CREATE_MESSAGE',
	VALIDATE_MESSAGE: 'VALIDATE_MESSAGE',
	ADD_LISTID_TO_FILTER: 'ADD_LISTID_TO_FILTER'
}
