module.exports = {
	CREATE_LIST : 'CREATE_LIST', 
	UPDATE_FILTER : 'UPDATE_FILTER',
	CREATE_MESSAGE : 'CREATE_MESSAGE',
	DELETE_MESSAGE : 'DELETE_MESSAGE',
	MOVE_MESSAGE : 'MOVE_MESSAGE', 
	ARCHIVE_MESSAGE : 'ARCHIVE_MESSAGE', 
	UNARCHIVE_MESSAGE : 'UNARCHIVE_MESSAGE'

}