module.exports = {
	CREATE_LIST: 'CREATE_LIST',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    ARCHIVE_MESSAGE: 'ARCHIVE_MESSAGE',
    UNARCHIVE_MESSAGE: 'UNARCHIVE_MESSAGE',
    MOVEUP_MESSAGE: 'MOVEUP_MESSAGE',
    MOVEDOWN_MESSAGE: 'MOVEDOWN_MESSAGE'
}