module.exports = {
	CREATE_LIST: 'CREATE_LIST',
	CREATE_MESSAGE: 'CREATE_MESSAGE',
	ARCHIVE_MESSAGE: 'ARCHIVE_MESSAGE',
	EXTRACT_MESSAGE: 'EXTRACT_MESSAGE',
	DELETE_MESSAGE: 'DELETE_MESSAGE',
	EXCEED_RANGE_ERROR: 'EXCEED_RANGE_ERROR',
	ALREADY_EXISTS_ERROR: 'ALREADY_EXISTS_ERROR',
}