const Constants = {
	STATUS_PENDING: 'STATUS_PENDING',
	STATUS_BUSY: 'STATUS_BUSY',
	STATUS_FREE: 'STATUS_FREE',
	STATUS_UNKNOWN: 'STATUS_UNKNOWN',
	GET_WEEK_APPOINTMENTS: 'GET_WEEK_APPOINTMENTS',
	INITIALIZE_TIMEFRAMES: 'INITIALIZE_TIMEFRAMES',
	SHOW_APPOINTMENT_FORM: 'SHOW_APPOINTMENT_FORM',
	HIDE_APPOINTMENT_FORM: 'HIDE_APPOINTMENT_FORM',
	SUBMIT_APPOINTMENT_REQUEST: 'SUBMIT_APPOINTMENT_REQUEST',
}

export const defaultDays = [{
	name: 'Monday'
}, {
	name: 'Tuesday'
}, {
	name: 'Wednesday'
}, {
	name: 'Thursday'
}, {
	name: 'Friday'
}]

export default Constants
