const Constants = {
	STATUS_PENDING: 'STATUS_PENDING',
	STATUS_BUSY: 'STATUS_BUSY',
	STATUS_FREE: 'STATUS_FREE',
	STATUS_UNKNOWN: 'STATUS_UNKNOWN',
	GET_WEEK_APPOINTMENTS: 'GET_WEEK_APPOINTMENTS'
}

export default Constants
