module.exports = {
    CREATE_LIST: 'CREATE_LIST',
    
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    MOVE_MESSAGE: 'MOVE_MESSAGE',
    TOGGLE_IS_ARCHIVED: 'TOGGLE_IS_ARCHIVED',
}