module.exports = {
	CREATE_LIST : 'CREATE_LIST', 
	UPDATE_FILTERS : 'UPDATE_FILTERS',
	ADD_FILTER : 'ADD_FILTER',
	REMOVE_FILTER : 'REMOVE_FILTER',
	CREATE_MESSAGE : 'CREATE_MESSAGE',
	DELETE_MESSAGE : 'DELETE_MESSAGE',
	MOVE_MESSAGE : 'MOVE_MESSAGE', 
	ARCHIVE_MESSAGE : 'ARCHIVE_MESSAGE', 
	UNARCHIVE_MESSAGE : 'UNARCHIVE_MESSAGE',
	CREATE_NOTIFICATION : 'CREATE_NOTIFICATION',
	DISMISS_NOTIFICATION : 'DISMISS_NOTIFICATION', 
	TRANSLATE_MESSAGES : 'TRANSLATE_MESSAGES',
	DISABLE_TRANSLATION : 'DISABLE_TRANSLATION',
	GET_LANGUAGES : 'GET_LANGUAGES'
}