module.exports = {
	CREATE_LIST: 'CREATE_LIST',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    ARCHIVE_MESSAGE: 'ARCHIVE_MESSAGE',
    UNARCHIVE_MESSAGE: 'UNARCHIVE_MESSAGE',
    MOVE_MESSAGES: 'MOVE_MESSAGE',
    HIDEMESSAGES: 'HIDEMESSAGES',
    UNHIDEMESSAGES: 'UNHIDEMESSAGES',
    DISMISS_NOTIFICATION: 'DISMISS_NOTIFICATION',
    ERROR_CREATE_MESSAGE: 'ERROR_CREATE_MESSAGE',
    TRANSLATE_MESSAGES: 'TRANSLATE_MESSAGES',
    GET_LANGUAGE_CODES: 'GET_LANGUAGE_CODES'
}