module.exports = {
    SELECT_CUSTOMER: 'SELECT_CUSTOMER',
    EDIT_CUSTOMER: 'EDIT_CUSTOMER',
    EDIT_CUSTOMER_RESPONSE: 'EDIT_CUSTOMER_RESPONSE',
    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
    REQUEST_CUSTOMERS: 'REQUEST_CUSTOMERS',
    REQUEST_CUSTOMERS_RESPONSE: 'REQUEST_CUSTOMERS_RESPONSE',
    
    REQUEST_CUSTOMER_TRANSACTIONS: 'REQUEST_CUSTOMER_TRANSACTIONS',
    REQUEST_CUSTOMER_TRANSACTIONS_RESPONSE: 'REQUEST_CUSTOMER_TRANSACTIONS_RESPONSE',
    
    REQUEST_CUSTOMER_ORDERS: 'REQUEST_CUSTOMER_ORDERS',
    REQUEST_CUSTOMER_ORDERS_RESPONSE: 'REQUEST_CUSTOMER_ORDERS_RESPONSE',

    // CREATE_LIST: 'CREATE_LIST',
    // TOGGLE_IS_SELECTED: 'TOGLE_IS_SELECTED',
    
    // CREATE_MESSAGE: 'CREATE_MESSAGE',
    // DELETE_MESSAGE: 'DELETE_MESSAGE',
    // MOVE_MESSAGE: 'MOVE_MESSAGE',
    // TOGGLE_IS_ARCHIVED: 'TOGGLE_IS_ARCHIVED',

    // UPDATE_OPTIONS: 'UPDATE_OPTIONS',
    // UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
    
    // TRANSLATE_ALL_MESSAGES: 'TRANSLATE_ALL_MESSAGES',
    // TRANSLATE_MESSAGE_RESPONSE: 'TRANSLATE_MESSAGE_RESPONSE',
    
    // REQUEST_LANGUAGES_RESPONSE: 'REQUEST_LANGUAGES_RESPONSE',
}