module.exports = {
    SELECT_CUSTOMER: 'SELECT_CUSTOMER',
    EDIT_CUSTOMER: 'EDIT_CUSTOMER',
    EDIT_CUSTOMER_RESPONSE: 'EDIT_CUSTOMER_RESPONSE',
    ADD_CUSTOMER: 'ADD_CUSTOMER',
    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
    DELETE_CUSTOMER: 'DELETE_CUSTOMER',
    DELETE_CUSTOMER_RESPONSE: 'DELETE_CUSTOMER_RESPONSE',
    REQUEST_CUSTOMERS: 'REQUEST_CUSTOMERS',
    REQUEST_CUSTOMERS_RESPONSE: 'REQUEST_CUSTOMERS_RESPONSE',
    
    REQUEST_CUSTOMER_TRANSACTIONS: 'REQUEST_CUSTOMER_TRANSACTIONS',
    REQUEST_CUSTOMER_TRANSACTIONS_RESPONSE: 'REQUEST_CUSTOMER_TRANSACTIONS_RESPONSE',
    
    REQUEST_CUSTOMER_ORDERS: 'REQUEST_CUSTOMER_ORDERS',
    REQUEST_CUSTOMER_ORDERS_RESPONSE: 'REQUEST_CUSTOMER_ORDERS_RESPONSE',
}