module.exports = {
	CREATE_LIST: 'CREATE_LIST',
	MOVE_MESSAGE: 'MOVE_MESSAGE',
	ARCHIVE_MESSAGE: 'ARCHIVE_MESSAGE',
	DELETE_MESSAGE: 'DELETE_MESSAGE',
	CREATE_MESSAGE: 'CREATE_MESSAGE',
	VALIDATE_MESSAGE: 'VALIDATE_MESSAGE',
	ADD_LISTID_TO_FILTER: 'ADD_LISTID_TO_FILTER',

	FAILURE_ON_CREATE_MESSAGE_TOO_MANY_CHARS: 'FAILURE_ON_CREATE_MESSAGE_TOO_MANY_CHARS',
	FAILURE_ON_CREATE_MESSAGE_NOT_UNIQUE: 'FAILURE_ON_CREATE_MESSAGE_NOT_UNIQUE',

	LANGUAGES_RECEIVED: 'LANGUAGES_RECEIVED',
	FAILURE_ON_LANGUAGES_RECEIVED: 'FAILURE_ON_LANGUAGES_RECEIVED',
	CANCEL_TRANSLATION: 'CANCEL_TRANSLATION'
}
