module.exports = {
    CREATE_LIST: 'CREATE_LIST',
    TOGGLE_IS_SELECTED: 'TOGLE_IS_SELECTED',
    
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    MOVE_MESSAGE: 'MOVE_MESSAGE',
    TOGGLE_IS_ARCHIVED: 'TOGGLE_IS_ARCHIVED',

    UPDATE_OPTIONS: 'UPDATE_OPTIONS',
}