module.exports = {
	CREATE_LIST: 'CREATE_LIST',
    ADD_MESSAGE: 'ADD_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    TOGGLE_ARCHIVE_MESSAGE: 'TOGGLE_ARCHIVE_MESSAGE',
    HIDE_MESSAGES:"HIDE_MESSAGES",
    SHOW_MESSAGES:"SHOW_MESSAGES",
    LANGUAGES_REQUESTED: "LANGUAGES_REQUESTED",
}