module.exports = {
	CREATE_LIST: 'CREATE_LIST',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    ARCHIVE_MESSAGE: 'ARCHIVE_MESSAGE',
    UNARCHIVE_MESSAGE: 'UNARCHIVE_MESSAGE',
    MOVE_MESSAGES: 'MOVE_MESSAGE',
    HIDEMESSAGES_LIST: 'HIDEMESSAGES_LIST',
    UNHIDEMESSAGES_LIST: 'UNHIDEMESSAGES_LIST',
    DISMISS_NOTIFICATION: 'DISMISS_NOTIFICATION'

}