module.exports = {
	CREATE_LIST: 'CREATE_LIST',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    ARCHIVE_MESSAGE: 'ARCHIVE_MESSAGE',
    UNARCHIVE_MESSAGE: 'UNARCHIVE_MESSAGE',
    MOVE_MESSAGE: 'MOVE_MESSAGE',
    FILTER_MESSAGES: 'FILTER_MESSAGES'
}